### PR TITLE
mlr3 compatability

### PR DESCRIPTION
**Pull request by mllg**

### CODE REVIEW

**Comment by mllg** [comment]
I guess we should provide an assertion for this in mlr3

**Comment by mllg** [comment]
I've just removed the assertion and added a test, the check is performed downstream in mlr3.

**Review by pat-s — COMMENTED** [review]
Thanks! Tests are not yet happy, could you have a look?

**Review by pat-s — APPROVED** [review]

**Comment by pat-s** [comment]
Failing CI is due to latest pushed on `main`.

**Pull request merged**
